package sublixt.math

public class Vec4(public val x: Float, public val y: Float, public val z: Float, public val w: Float) {
    public companion object {
        public val zero: Vec4 = Vec4(0f, 0f, 0f, 0f)
        public fun invoke(): Vec4 = zero
    }

    public fun get(index: Int): Float =
            when (index) {
                0 -> x
                1 -> y
                2 -> z
                3 -> w
                else -> throw IndexOutOfBoundsException("[Vec4](get(int)): " + index + " not in range [0, 3]")
            }

    public fun minus(): Vec4 = Vec4(-x, -y, -z, -w)

    public val magnitudeSquared: Float get() = dot(this)
    public val magnitude: Float get() = sqrt(magnitudeSquared)
    public val normal: Vec4 get() = div(magnitude)

    public fun project(onto: Vec4): Vec4 =
            onto * (dot(onto) / onto.magnitude)

    public fun dot(other: Vec4): Float = x * other.x + y * other.y + z * other.z + w * other.w

    public fun plus(scalar: Float): Vec4 = Vec4(x + scalar, y + scalar, z + scalar, w + scalar)
    public fun minus(scalar: Float): Vec4 = Vec4(x - scalar, y - scalar, z - scalar, w - scalar)
    public fun times(scalar: Float): Vec4 = Vec4(x * scalar, y * scalar, z * scalar, w * scalar)
    public fun div(scalar: Float): Vec4 = Vec4(x / scalar, y / scalar, z / scalar, w / scalar)

    public fun plus(scalar: Int): Vec4 = Vec4(x + scalar, y + scalar, z + scalar, w + scalar)
    public fun minus(scalar: Int): Vec4 = Vec4(x - scalar, y - scalar, z - scalar, w - scalar)
    public fun times(scalar: Int): Vec4 = Vec4(x * scalar, y * scalar, z * scalar, w * scalar)
    public fun div(scalar: Int): Vec4 = Vec4(x / scalar, y / scalar, z / scalar, w / scalar)

    public fun plus(other: Vec4): Vec4 = Vec4(x + other.x, y + other.y, z + other.z, w + other.w)
    public fun minus(other: Vec4): Vec4 = Vec4(x - other.x, y - other.y, z - other.z, w - other.w)
    public fun times(other: Vec4): Vec4 = Vec4(x * other.x, y * other.y, z * other.z, w * other.w)
    public fun div(other: Vec4): Vec4 = Vec4(x / other.x, y / other.y, z / other.z, w / other.w)

    public fun min(other: Vec4): Vec4 =
            Vec4(
                    x.min(other.x),
                    y.min(other.y),
                    y.min(other.z),
                    w.min(other.w)
            )

    public fun min(scalar: Float): Vec4 =
            Vec4(
                    x.min(scalar),
                    y.min(scalar),
                    z.min(scalar),
                    w.min(scalar)
            )

    public fun min(scalar: Int): Vec4 =
            Vec4(
                    x.min(scalar),
                    y.min(scalar),
                    z.min(scalar),
                    w.min(scalar)
            )

    public fun max(other: Vec4): Vec4 =
            Vec4(
                    x.max(other.x),
                    y.max(other.y),
                    z.max(other.z),
                    w.max(other.w)
            )

    public fun max(scalar: Float): Vec4 =
            Vec4(
                    x.max(scalar),
                    y.max(scalar),
                    z.max(scalar),
                    w.max(scalar)
            )

    public fun max(scalar: Int): Vec4 =
            Vec4(
                    x.max(scalar),
                    y.max(scalar),
                    z.max(scalar),
                    w.max(scalar)
            )

    public fun clamp(min: Vec4, max: Vec4): Vec4 =
            Vec4(
                    x.clamp(min.x, max.x),
                    y.clamp(min.y, max.y),
                    z.clamp(min.z, max.z),
                    w.clamp(min.w, min.w)
            )

    public fun clamp(min: Vec4, max: Float): Vec4 =
            Vec4(
                    x.clamp(min.x, max),
                    y.clamp(min.y, max),
                    z.clamp(min.z, max),
                    w.clamp(min.w, max)
            )

    public fun clamp(min: Vec4, max: Int): Vec4 =
            Vec4(
                    x.clamp(min.x, max),
                    y.clamp(min.y, max),
                    z.clamp(min.z, max),
                    w.clamp(min.w, max)
            )

    public fun clamp(min: Float, max: Vec4): Vec4 =
            Vec4(
                    x.clamp(min, max.x),
                    y.clamp(min, max.y),
                    z.clamp(min, max.z),
                    w.clamp(min, max.w)
            )

    public fun clamp(min: Int, max: Vec4): Vec4 =
            Vec4(
                    x.clamp(min, max.x),
                    y.clamp(min, max.y),
                    z.clamp(min, max.z),
                    w.clamp(min, max.w)
            )

    public fun clamp(min: Float, max: Float): Vec4 =
            Vec4(
                    x.clamp(min, max),
                    y.clamp(min, max),
                    z.clamp(min, max),
                    w.clamp(min, max)
            )

    public fun clamp(min: Float, max: Int): Vec4 =
            Vec4(
                    x.clamp(min, max),
                    y.clamp(min, max),
                    z.clamp(min, max),
                    w.clamp(min, max)
            )

    public fun clamp(min: Int, max: Float): Vec4 =
            Vec4(
                    x.clamp(min, max),
                    y.clamp(min, max),
                    z.clamp(min, max),
                    w.clamp(min, max)
            )

    public fun clamp(min: Int, max: Int): Vec4 =
            Vec4(
                    x.clamp(min, max),
                    y.clamp(min, max),
                    z.clamp(min, max),
                    w.clamp(min, max)
            )

    public fun lerp(to: Vec4, speed: Float): Vec4 {
        val invspeed = 1f - speed
        return Vec4(
                (x * invspeed) + (to.x * speed),
                (y * invspeed) + (to.y * speed),
                (z * invspeed) + (to.z * speed),
                (w * invspeed) + (to.w * speed)
        )
    }

    public val ww: Vec2 get() = Vec2(w, w)
    public val wx: Vec2 get() = Vec2(w, x)
    public val wy: Vec2 get() = Vec2(w, y)
    public val wz: Vec2 get() = Vec2(w, z)
    public val xw: Vec2 get() = Vec2(x, w)
    public val xx: Vec2 get() = Vec2(x, x)
    public val xy: Vec2 get() = Vec2(x, y)
    public val xz: Vec2 get() = Vec2(x, z)
    public val yw: Vec2 get() = Vec2(y, w)
    public val yx: Vec2 get() = Vec2(y, x)
    public val yy: Vec2 get() = Vec2(y, y)
    public val yz: Vec2 get() = Vec2(y, z)
    public val zw: Vec2 get() = Vec2(z, w)
    public val zx: Vec2 get() = Vec2(z, x)
    public val zy: Vec2 get() = Vec2(z, y)
    public val zz: Vec2 get() = Vec2(z, z)

    public val www: Vec3 get() = Vec3(w, w, w)
    public val wwx: Vec3 get() = Vec3(w, w, x)
    public val wwy: Vec3 get() = Vec3(w, w, y)
    public val wwz: Vec3 get() = Vec3(w, w, z)
    public val wxw: Vec3 get() = Vec3(w, x, w)
    public val wxx: Vec3 get() = Vec3(w, x, x)
    public val wxy: Vec3 get() = Vec3(w, x, y)
    public val wxz: Vec3 get() = Vec3(w, x, z)
    public val wyw: Vec3 get() = Vec3(w, y, w)
    public val wyx: Vec3 get() = Vec3(w, y, x)
    public val wyy: Vec3 get() = Vec3(w, y, y)
    public val wyz: Vec3 get() = Vec3(w, y, z)
    public val wzw: Vec3 get() = Vec3(w, z, w)
    public val wzx: Vec3 get() = Vec3(w, z, x)
    public val wzy: Vec3 get() = Vec3(w, z, y)
    public val wzz: Vec3 get() = Vec3(w, z, z)
    public val xww: Vec3 get() = Vec3(x, w, w)
    public val xwx: Vec3 get() = Vec3(x, w, x)
    public val xwy: Vec3 get() = Vec3(x, w, y)
    public val xwz: Vec3 get() = Vec3(x, w, z)
    public val xxw: Vec3 get() = Vec3(x, x, w)
    public val xxx: Vec3 get() = Vec3(x, x, x)
    public val xxy: Vec3 get() = Vec3(x, x, y)
    public val xxz: Vec3 get() = Vec3(x, x, z)
    public val xyw: Vec3 get() = Vec3(x, y, w)
    public val xyx: Vec3 get() = Vec3(x, y, x)
    public val xyy: Vec3 get() = Vec3(x, y, y)
    public val xyz: Vec3 get() = Vec3(x, y, z)
    public val xzw: Vec3 get() = Vec3(x, z, w)
    public val xzx: Vec3 get() = Vec3(x, z, x)
    public val xzy: Vec3 get() = Vec3(x, z, y)
    public val xzz: Vec3 get() = Vec3(x, z, z)
    public val yww: Vec3 get() = Vec3(y, w, w)
    public val ywx: Vec3 get() = Vec3(y, w, x)
    public val ywy: Vec3 get() = Vec3(y, w, y)
    public val ywz: Vec3 get() = Vec3(y, w, z)
    public val yxw: Vec3 get() = Vec3(y, x, w)
    public val yxx: Vec3 get() = Vec3(y, x, x)
    public val yxy: Vec3 get() = Vec3(y, x, y)
    public val yxz: Vec3 get() = Vec3(y, x, z)
    public val yyw: Vec3 get() = Vec3(y, y, w)
    public val yyx: Vec3 get() = Vec3(y, y, x)
    public val yyy: Vec3 get() = Vec3(y, y, y)
    public val yyz: Vec3 get() = Vec3(y, y, z)
    public val yzw: Vec3 get() = Vec3(y, z, w)
    public val yzx: Vec3 get() = Vec3(y, z, x)
    public val yzy: Vec3 get() = Vec3(y, z, y)
    public val yzz: Vec3 get() = Vec3(y, z, z)
    public val zww: Vec3 get() = Vec3(z, w, w)
    public val zwx: Vec3 get() = Vec3(z, w, x)
    public val zwy: Vec3 get() = Vec3(z, w, y)
    public val zwz: Vec3 get() = Vec3(z, w, z)
    public val zxw: Vec3 get() = Vec3(z, x, w)
    public val zxx: Vec3 get() = Vec3(z, x, x)
    public val zxy: Vec3 get() = Vec3(z, x, y)
    public val zxz: Vec3 get() = Vec3(z, x, z)
    public val zyw: Vec3 get() = Vec3(z, y, w)
    public val zyx: Vec3 get() = Vec3(z, y, x)
    public val zyy: Vec3 get() = Vec3(z, y, y)
    public val zyz: Vec3 get() = Vec3(z, y, z)
    public val zzw: Vec3 get() = Vec3(z, z, w)
    public val zzx: Vec3 get() = Vec3(z, z, x)
    public val zzy: Vec3 get() = Vec3(z, z, y)
    public val zzz: Vec3 get() = Vec3(z, z, z)

    public val wwww: Vec4 get() = Vec4(w, w, w, w)
    public val wwwx: Vec4 get() = Vec4(w, w, w, x)
    public val wwwy: Vec4 get() = Vec4(w, w, w, y)
    public val wwwz: Vec4 get() = Vec4(w, w, w, z)
    public val wwxw: Vec4 get() = Vec4(w, w, x, w)
    public val wwxx: Vec4 get() = Vec4(w, w, x, x)
    public val wwxy: Vec4 get() = Vec4(w, w, x, y)
    public val wwxz: Vec4 get() = Vec4(w, w, x, z)
    public val wwyw: Vec4 get() = Vec4(w, w, y, w)
    public val wwyx: Vec4 get() = Vec4(w, w, y, x)
    public val wwyy: Vec4 get() = Vec4(w, w, y, y)
    public val wwyz: Vec4 get() = Vec4(w, w, y, z)
    public val wwzw: Vec4 get() = Vec4(w, w, z, w)
    public val wwzx: Vec4 get() = Vec4(w, w, z, x)
    public val wwzy: Vec4 get() = Vec4(w, w, z, y)
    public val wwzz: Vec4 get() = Vec4(w, w, z, z)
    public val wxww: Vec4 get() = Vec4(w, x, w, w)
    public val wxwx: Vec4 get() = Vec4(w, x, w, x)
    public val wxwy: Vec4 get() = Vec4(w, x, w, y)
    public val wxwz: Vec4 get() = Vec4(w, x, w, z)
    public val wxxw: Vec4 get() = Vec4(w, x, x, w)
    public val wxxx: Vec4 get() = Vec4(w, x, x, x)
    public val wxxy: Vec4 get() = Vec4(w, x, x, y)
    public val wxxz: Vec4 get() = Vec4(w, x, x, z)
    public val wxyw: Vec4 get() = Vec4(w, x, y, w)
    public val wxyx: Vec4 get() = Vec4(w, x, y, x)
    public val wxyy: Vec4 get() = Vec4(w, x, y, y)
    public val wxyz: Vec4 get() = Vec4(w, x, y, z)
    public val wxzw: Vec4 get() = Vec4(w, x, z, w)
    public val wxzx: Vec4 get() = Vec4(w, x, z, x)
    public val wxzy: Vec4 get() = Vec4(w, x, z, y)
    public val wxzz: Vec4 get() = Vec4(w, x, z, z)
    public val wyww: Vec4 get() = Vec4(w, y, w, w)
    public val wywx: Vec4 get() = Vec4(w, y, w, x)
    public val wywy: Vec4 get() = Vec4(w, y, w, y)
    public val wywz: Vec4 get() = Vec4(w, y, w, z)
    public val wyxw: Vec4 get() = Vec4(w, y, x, w)
    public val wyxx: Vec4 get() = Vec4(w, y, x, x)
    public val wyxy: Vec4 get() = Vec4(w, y, x, y)
    public val wyxz: Vec4 get() = Vec4(w, y, x, z)
    public val wyyw: Vec4 get() = Vec4(w, y, y, w)
    public val wyyx: Vec4 get() = Vec4(w, y, y, x)
    public val wyyy: Vec4 get() = Vec4(w, y, y, y)
    public val wyyz: Vec4 get() = Vec4(w, y, y, z)
    public val wyzw: Vec4 get() = Vec4(w, y, z, w)
    public val wyzx: Vec4 get() = Vec4(w, y, z, x)
    public val wyzy: Vec4 get() = Vec4(w, y, z, y)
    public val wyzz: Vec4 get() = Vec4(w, y, z, z)
    public val wzww: Vec4 get() = Vec4(w, z, w, w)
    public val wzwx: Vec4 get() = Vec4(w, z, w, x)
    public val wzwy: Vec4 get() = Vec4(w, z, w, y)
    public val wzwz: Vec4 get() = Vec4(w, z, w, z)
    public val wzxw: Vec4 get() = Vec4(w, z, x, w)
    public val wzxx: Vec4 get() = Vec4(w, z, x, x)
    public val wzxy: Vec4 get() = Vec4(w, z, x, y)
    public val wzxz: Vec4 get() = Vec4(w, z, x, z)
    public val wzyw: Vec4 get() = Vec4(w, z, y, w)
    public val wzyx: Vec4 get() = Vec4(w, z, y, x)
    public val wzyy: Vec4 get() = Vec4(w, z, y, y)
    public val wzyz: Vec4 get() = Vec4(w, z, y, z)
    public val wzzw: Vec4 get() = Vec4(w, z, z, w)
    public val wzzx: Vec4 get() = Vec4(w, z, z, x)
    public val wzzy: Vec4 get() = Vec4(w, z, z, y)
    public val wzzz: Vec4 get() = Vec4(w, z, z, z)
    public val xwww: Vec4 get() = Vec4(x, w, w, w)
    public val xwwx: Vec4 get() = Vec4(x, w, w, x)
    public val xwwy: Vec4 get() = Vec4(x, w, w, y)
    public val xwwz: Vec4 get() = Vec4(x, w, w, z)
    public val xwxw: Vec4 get() = Vec4(x, w, x, w)
    public val xwxx: Vec4 get() = Vec4(x, w, x, x)
    public val xwxy: Vec4 get() = Vec4(x, w, x, y)
    public val xwxz: Vec4 get() = Vec4(x, w, x, z)
    public val xwyw: Vec4 get() = Vec4(x, w, y, w)
    public val xwyx: Vec4 get() = Vec4(x, w, y, x)
    public val xwyy: Vec4 get() = Vec4(x, w, y, y)
    public val xwyz: Vec4 get() = Vec4(x, w, y, z)
    public val xwzw: Vec4 get() = Vec4(x, w, z, w)
    public val xwzx: Vec4 get() = Vec4(x, w, z, x)
    public val xwzy: Vec4 get() = Vec4(x, w, z, y)
    public val xwzz: Vec4 get() = Vec4(x, w, z, z)
    public val xxww: Vec4 get() = Vec4(x, x, w, w)
    public val xxwx: Vec4 get() = Vec4(x, x, w, x)
    public val xxwy: Vec4 get() = Vec4(x, x, w, y)
    public val xxwz: Vec4 get() = Vec4(x, x, w, z)
    public val xxxw: Vec4 get() = Vec4(x, x, x, w)
    public val xxxx: Vec4 get() = Vec4(x, x, x, x)
    public val xxxy: Vec4 get() = Vec4(x, x, x, y)
    public val xxxz: Vec4 get() = Vec4(x, x, x, z)
    public val xxyw: Vec4 get() = Vec4(x, x, y, w)
    public val xxyx: Vec4 get() = Vec4(x, x, y, x)
    public val xxyy: Vec4 get() = Vec4(x, x, y, y)
    public val xxyz: Vec4 get() = Vec4(x, x, y, z)
    public val xxzw: Vec4 get() = Vec4(x, x, z, w)
    public val xxzx: Vec4 get() = Vec4(x, x, z, x)
    public val xxzy: Vec4 get() = Vec4(x, x, z, y)
    public val xxzz: Vec4 get() = Vec4(x, x, z, z)
    public val xyww: Vec4 get() = Vec4(x, y, w, w)
    public val xywx: Vec4 get() = Vec4(x, y, w, x)
    public val xywy: Vec4 get() = Vec4(x, y, w, y)
    public val xywz: Vec4 get() = Vec4(x, y, w, z)
    public val xyxw: Vec4 get() = Vec4(x, y, x, w)
    public val xyxx: Vec4 get() = Vec4(x, y, x, x)
    public val xyxy: Vec4 get() = Vec4(x, y, x, y)
    public val xyxz: Vec4 get() = Vec4(x, y, x, z)
    public val xyyw: Vec4 get() = Vec4(x, y, y, w)
    public val xyyx: Vec4 get() = Vec4(x, y, y, x)
    public val xyyy: Vec4 get() = Vec4(x, y, y, y)
    public val xyyz: Vec4 get() = Vec4(x, y, y, z)
    public val xyzw: Vec4 get() = Vec4(x, y, z, w)
    public val xyzx: Vec4 get() = Vec4(x, y, z, x)
    public val xyzy: Vec4 get() = Vec4(x, y, z, y)
    public val xyzz: Vec4 get() = Vec4(x, y, z, z)
    public val xzww: Vec4 get() = Vec4(x, z, w, w)
    public val xzwx: Vec4 get() = Vec4(x, z, w, x)
    public val xzwy: Vec4 get() = Vec4(x, z, w, y)
    public val xzwz: Vec4 get() = Vec4(x, z, w, z)
    public val xzxw: Vec4 get() = Vec4(x, z, x, w)
    public val xzxx: Vec4 get() = Vec4(x, z, x, x)
    public val xzxy: Vec4 get() = Vec4(x, z, x, y)
    public val xzxz: Vec4 get() = Vec4(x, z, x, z)
    public val xzyw: Vec4 get() = Vec4(x, z, y, w)
    public val xzyx: Vec4 get() = Vec4(x, z, y, x)
    public val xzyy: Vec4 get() = Vec4(x, z, y, y)
    public val xzyz: Vec4 get() = Vec4(x, z, y, z)
    public val xzzw: Vec4 get() = Vec4(x, z, z, w)
    public val xzzx: Vec4 get() = Vec4(x, z, z, x)
    public val xzzy: Vec4 get() = Vec4(x, z, z, y)
    public val xzzz: Vec4 get() = Vec4(x, z, z, z)
    public val ywww: Vec4 get() = Vec4(y, w, w, w)
    public val ywwx: Vec4 get() = Vec4(y, w, w, x)
    public val ywwy: Vec4 get() = Vec4(y, w, w, y)
    public val ywwz: Vec4 get() = Vec4(y, w, w, z)
    public val ywxw: Vec4 get() = Vec4(y, w, x, w)
    public val ywxx: Vec4 get() = Vec4(y, w, x, x)
    public val ywxy: Vec4 get() = Vec4(y, w, x, y)
    public val ywxz: Vec4 get() = Vec4(y, w, x, z)
    public val ywyw: Vec4 get() = Vec4(y, w, y, w)
    public val ywyx: Vec4 get() = Vec4(y, w, y, x)
    public val ywyy: Vec4 get() = Vec4(y, w, y, y)
    public val ywyz: Vec4 get() = Vec4(y, w, y, z)
    public val ywzw: Vec4 get() = Vec4(y, w, z, w)
    public val ywzx: Vec4 get() = Vec4(y, w, z, x)
    public val ywzy: Vec4 get() = Vec4(y, w, z, y)
    public val ywzz: Vec4 get() = Vec4(y, w, z, z)
    public val yxww: Vec4 get() = Vec4(y, x, w, w)
    public val yxwx: Vec4 get() = Vec4(y, x, w, x)
    public val yxwy: Vec4 get() = Vec4(y, x, w, y)
    public val yxwz: Vec4 get() = Vec4(y, x, w, z)
    public val yxxw: Vec4 get() = Vec4(y, x, x, w)
    public val yxxx: Vec4 get() = Vec4(y, x, x, x)
    public val yxxy: Vec4 get() = Vec4(y, x, x, y)
    public val yxxz: Vec4 get() = Vec4(y, x, x, z)
    public val yxyw: Vec4 get() = Vec4(y, x, y, w)
    public val yxyx: Vec4 get() = Vec4(y, x, y, x)
    public val yxyy: Vec4 get() = Vec4(y, x, y, y)
    public val yxyz: Vec4 get() = Vec4(y, x, y, z)
    public val yxzw: Vec4 get() = Vec4(y, x, z, w)
    public val yxzx: Vec4 get() = Vec4(y, x, z, x)
    public val yxzy: Vec4 get() = Vec4(y, x, z, y)
    public val yxzz: Vec4 get() = Vec4(y, x, z, z)
    public val yyww: Vec4 get() = Vec4(y, y, w, w)
    public val yywx: Vec4 get() = Vec4(y, y, w, x)
    public val yywy: Vec4 get() = Vec4(y, y, w, y)
    public val yywz: Vec4 get() = Vec4(y, y, w, z)
    public val yyxw: Vec4 get() = Vec4(y, y, x, w)
    public val yyxx: Vec4 get() = Vec4(y, y, x, x)
    public val yyxy: Vec4 get() = Vec4(y, y, x, y)
    public val yyxz: Vec4 get() = Vec4(y, y, x, z)
    public val yyyw: Vec4 get() = Vec4(y, y, y, w)
    public val yyyx: Vec4 get() = Vec4(y, y, y, x)
    public val yyyy: Vec4 get() = Vec4(y, y, y, y)
    public val yyyz: Vec4 get() = Vec4(y, y, y, z)
    public val yyzw: Vec4 get() = Vec4(y, y, z, w)
    public val yyzx: Vec4 get() = Vec4(y, y, z, x)
    public val yyzy: Vec4 get() = Vec4(y, y, z, y)
    public val yyzz: Vec4 get() = Vec4(y, y, z, z)
    public val yzww: Vec4 get() = Vec4(y, z, w, w)
    public val yzwx: Vec4 get() = Vec4(y, z, w, x)
    public val yzwy: Vec4 get() = Vec4(y, z, w, y)
    public val yzwz: Vec4 get() = Vec4(y, z, w, z)
    public val yzxw: Vec4 get() = Vec4(y, z, x, w)
    public val yzxx: Vec4 get() = Vec4(y, z, x, x)
    public val yzxy: Vec4 get() = Vec4(y, z, x, y)
    public val yzxz: Vec4 get() = Vec4(y, z, x, z)
    public val yzyw: Vec4 get() = Vec4(y, z, y, w)
    public val yzyx: Vec4 get() = Vec4(y, z, y, x)
    public val yzyy: Vec4 get() = Vec4(y, z, y, y)
    public val yzyz: Vec4 get() = Vec4(y, z, y, z)
    public val yzzw: Vec4 get() = Vec4(y, z, z, w)
    public val yzzx: Vec4 get() = Vec4(y, z, z, x)
    public val yzzy: Vec4 get() = Vec4(y, z, z, y)
    public val yzzz: Vec4 get() = Vec4(y, z, z, z)
    public val zwww: Vec4 get() = Vec4(z, w, w, w)
    public val zwwx: Vec4 get() = Vec4(z, w, w, x)
    public val zwwy: Vec4 get() = Vec4(z, w, w, y)
    public val zwwz: Vec4 get() = Vec4(z, w, w, z)
    public val zwxw: Vec4 get() = Vec4(z, w, x, w)
    public val zwxx: Vec4 get() = Vec4(z, w, x, x)
    public val zwxy: Vec4 get() = Vec4(z, w, x, y)
    public val zwxz: Vec4 get() = Vec4(z, w, x, z)
    public val zwyw: Vec4 get() = Vec4(z, w, y, w)
    public val zwyx: Vec4 get() = Vec4(z, w, y, x)
    public val zwyy: Vec4 get() = Vec4(z, w, y, y)
    public val zwyz: Vec4 get() = Vec4(z, w, y, z)
    public val zwzw: Vec4 get() = Vec4(z, w, z, w)
    public val zwzx: Vec4 get() = Vec4(z, w, z, x)
    public val zwzy: Vec4 get() = Vec4(z, w, z, y)
    public val zwzz: Vec4 get() = Vec4(z, w, z, z)
    public val zxww: Vec4 get() = Vec4(z, x, w, w)
    public val zxwx: Vec4 get() = Vec4(z, x, w, x)
    public val zxwy: Vec4 get() = Vec4(z, x, w, y)
    public val zxwz: Vec4 get() = Vec4(z, x, w, z)
    public val zxxw: Vec4 get() = Vec4(z, x, x, w)
    public val zxxx: Vec4 get() = Vec4(z, x, x, x)
    public val zxxy: Vec4 get() = Vec4(z, x, x, y)
    public val zxxz: Vec4 get() = Vec4(z, x, x, z)
    public val zxyw: Vec4 get() = Vec4(z, x, y, w)
    public val zxyx: Vec4 get() = Vec4(z, x, y, x)
    public val zxyy: Vec4 get() = Vec4(z, x, y, y)
    public val zxyz: Vec4 get() = Vec4(z, x, y, z)
    public val zxzw: Vec4 get() = Vec4(z, x, z, w)
    public val zxzx: Vec4 get() = Vec4(z, x, z, x)
    public val zxzy: Vec4 get() = Vec4(z, x, z, y)
    public val zxzz: Vec4 get() = Vec4(z, x, z, z)
    public val zyww: Vec4 get() = Vec4(z, y, w, w)
    public val zywx: Vec4 get() = Vec4(z, y, w, x)
    public val zywy: Vec4 get() = Vec4(z, y, w, y)
    public val zywz: Vec4 get() = Vec4(z, y, w, z)
    public val zyxw: Vec4 get() = Vec4(z, y, x, w)
    public val zyxx: Vec4 get() = Vec4(z, y, x, x)
    public val zyxy: Vec4 get() = Vec4(z, y, x, y)
    public val zyxz: Vec4 get() = Vec4(z, y, x, z)
    public val zyyw: Vec4 get() = Vec4(z, y, y, w)
    public val zyyx: Vec4 get() = Vec4(z, y, y, x)
    public val zyyy: Vec4 get() = Vec4(z, y, y, y)
    public val zyyz: Vec4 get() = Vec4(z, y, y, z)
    public val zyzw: Vec4 get() = Vec4(z, y, z, w)
    public val zyzx: Vec4 get() = Vec4(z, y, z, x)
    public val zyzy: Vec4 get() = Vec4(z, y, z, y)
    public val zyzz: Vec4 get() = Vec4(z, y, z, z)
    public val zzww: Vec4 get() = Vec4(z, z, w, w)
    public val zzwx: Vec4 get() = Vec4(z, z, w, x)
    public val zzwy: Vec4 get() = Vec4(z, z, w, y)
    public val zzwz: Vec4 get() = Vec4(z, z, w, z)
    public val zzxw: Vec4 get() = Vec4(z, z, x, w)
    public val zzxx: Vec4 get() = Vec4(z, z, x, x)
    public val zzxy: Vec4 get() = Vec4(z, z, x, y)
    public val zzxz: Vec4 get() = Vec4(z, z, x, z)
    public val zzyw: Vec4 get() = Vec4(z, z, y, w)
    public val zzyx: Vec4 get() = Vec4(z, z, y, x)
    public val zzyy: Vec4 get() = Vec4(z, z, y, y)
    public val zzyz: Vec4 get() = Vec4(z, z, y, z)
    public val zzzw: Vec4 get() = Vec4(z, z, z, w)
    public val zzzx: Vec4 get() = Vec4(z, z, z, x)
    public val zzzy: Vec4 get() = Vec4(z, z, z, y)
    public val zzzz: Vec4 get() = Vec4(z, z, z, z)

    public val s: Float get() = x
    public val t: Float get() = y
    public val p: Float get() = z
    public val q: Float get() = w

    public val ss: Vec2 get() = Vec2(x, x)
    public val st: Vec2 get() = Vec2(x, y)
    public val sp: Vec2 get() = Vec2(x, z)
    public val sq: Vec2 get() = Vec2(x, w)
    public val ts: Vec2 get() = Vec2(y, x)
    public val tt: Vec2 get() = Vec2(y, y)
    public val tp: Vec2 get() = Vec2(y, z)
    public val tq: Vec2 get() = Vec2(y, w)
    public val ps: Vec2 get() = Vec2(z, x)
    public val pt: Vec2 get() = Vec2(z, y)
    public val pp: Vec2 get() = Vec2(z, z)
    public val pq: Vec2 get() = Vec2(z, w)
    public val qs: Vec2 get() = Vec2(w, x)
    public val qt: Vec2 get() = Vec2(w, y)
    public val qp: Vec2 get() = Vec2(w, z)
    public val qq: Vec2 get() = Vec2(w, w)

    public val sss: Vec3 get() = Vec3(x, x, x)
    public val sst: Vec3 get() = Vec3(x, x, y)
    public val ssp: Vec3 get() = Vec3(x, x, z)
    public val ssq: Vec3 get() = Vec3(x, x, w)
    public val sts: Vec3 get() = Vec3(x, y, x)
    public val stt: Vec3 get() = Vec3(x, y, y)
    public val stp: Vec3 get() = Vec3(x, y, z)
    public val stq: Vec3 get() = Vec3(x, y, w)
    public val sps: Vec3 get() = Vec3(x, z, x)
    public val spt: Vec3 get() = Vec3(x, z, y)
    public val spp: Vec3 get() = Vec3(x, z, z)
    public val spq: Vec3 get() = Vec3(x, z, w)
    public val sqs: Vec3 get() = Vec3(x, w, x)
    public val sqt: Vec3 get() = Vec3(x, w, y)
    public val sqp: Vec3 get() = Vec3(x, w, z)
    public val sqq: Vec3 get() = Vec3(x, w, w)
    public val tss: Vec3 get() = Vec3(y, x, x)
    public val tst: Vec3 get() = Vec3(y, x, y)
    public val tsp: Vec3 get() = Vec3(y, x, z)
    public val tsq: Vec3 get() = Vec3(y, x, w)
    public val tts: Vec3 get() = Vec3(y, y, x)
    public val ttt: Vec3 get() = Vec3(y, y, y)
    public val ttp: Vec3 get() = Vec3(y, y, z)
    public val ttq: Vec3 get() = Vec3(y, y, w)
    public val tps: Vec3 get() = Vec3(y, z, x)
    public val tpt: Vec3 get() = Vec3(y, z, y)
    public val tpp: Vec3 get() = Vec3(y, z, z)
    public val tpq: Vec3 get() = Vec3(y, z, w)
    public val tqs: Vec3 get() = Vec3(y, w, x)
    public val tqt: Vec3 get() = Vec3(y, w, y)
    public val tqp: Vec3 get() = Vec3(y, w, z)
    public val tqq: Vec3 get() = Vec3(y, w, w)
    public val pss: Vec3 get() = Vec3(z, x, x)
    public val pst: Vec3 get() = Vec3(z, x, y)
    public val psp: Vec3 get() = Vec3(z, x, z)
    public val psq: Vec3 get() = Vec3(z, x, w)
    public val pts: Vec3 get() = Vec3(z, y, x)
    public val ptt: Vec3 get() = Vec3(z, y, y)
    public val ptp: Vec3 get() = Vec3(z, y, z)
    public val ptq: Vec3 get() = Vec3(z, y, w)
    public val pps: Vec3 get() = Vec3(z, z, x)
    public val ppt: Vec3 get() = Vec3(z, z, y)
    public val ppp: Vec3 get() = Vec3(z, z, z)
    public val ppq: Vec3 get() = Vec3(z, z, w)
    public val pqs: Vec3 get() = Vec3(z, w, x)
    public val pqt: Vec3 get() = Vec3(z, w, y)
    public val pqp: Vec3 get() = Vec3(z, w, z)
    public val pqq: Vec3 get() = Vec3(z, w, w)
    public val qss: Vec3 get() = Vec3(w, x, x)
    public val qst: Vec3 get() = Vec3(w, x, y)
    public val qsp: Vec3 get() = Vec3(w, x, z)
    public val qsq: Vec3 get() = Vec3(w, x, w)
    public val qts: Vec3 get() = Vec3(w, y, x)
    public val qtt: Vec3 get() = Vec3(w, y, y)
    public val qtp: Vec3 get() = Vec3(w, y, z)
    public val qtq: Vec3 get() = Vec3(w, y, w)
    public val qps: Vec3 get() = Vec3(w, z, x)
    public val qpt: Vec3 get() = Vec3(w, z, y)
    public val qpp: Vec3 get() = Vec3(w, z, z)
    public val qpq: Vec3 get() = Vec3(w, z, w)
    public val qqs: Vec3 get() = Vec3(w, w, x)
    public val qqt: Vec3 get() = Vec3(w, w, y)
    public val qqp: Vec3 get() = Vec3(w, w, z)
    public val qqq: Vec3 get() = Vec3(w, w, w)

    public val ssss: Vec4 get() = Vec4(x, x, x, x)
    public val ssst: Vec4 get() = Vec4(x, x, x, y)
    public val sssp: Vec4 get() = Vec4(x, x, x, z)
    public val sssq: Vec4 get() = Vec4(x, x, x, w)
    public val ssts: Vec4 get() = Vec4(x, x, y, x)
    public val sstt: Vec4 get() = Vec4(x, x, y, y)
    public val sstp: Vec4 get() = Vec4(x, x, y, z)
    public val sstq: Vec4 get() = Vec4(x, x, y, w)
    public val ssps: Vec4 get() = Vec4(x, x, z, x)
    public val sspt: Vec4 get() = Vec4(x, x, z, y)
    public val sspp: Vec4 get() = Vec4(x, x, z, z)
    public val sspq: Vec4 get() = Vec4(x, x, z, w)
    public val ssqs: Vec4 get() = Vec4(x, x, w, x)
    public val ssqt: Vec4 get() = Vec4(x, x, w, y)
    public val ssqp: Vec4 get() = Vec4(x, x, w, z)
    public val ssqq: Vec4 get() = Vec4(x, x, w, w)
    public val stss: Vec4 get() = Vec4(x, y, x, x)
    public val stst: Vec4 get() = Vec4(x, y, x, y)
    public val stsp: Vec4 get() = Vec4(x, y, x, z)
    public val stsq: Vec4 get() = Vec4(x, y, x, w)
    public val stts: Vec4 get() = Vec4(x, y, y, x)
    public val sttt: Vec4 get() = Vec4(x, y, y, y)
    public val sttp: Vec4 get() = Vec4(x, y, y, z)
    public val sttq: Vec4 get() = Vec4(x, y, y, w)
    public val stps: Vec4 get() = Vec4(x, y, z, x)
    public val stpt: Vec4 get() = Vec4(x, y, z, y)
    public val stpp: Vec4 get() = Vec4(x, y, z, z)
    public val stpq: Vec4 get() = Vec4(x, y, z, w)
    public val stqs: Vec4 get() = Vec4(x, y, w, x)
    public val stqt: Vec4 get() = Vec4(x, y, w, y)
    public val stqp: Vec4 get() = Vec4(x, y, w, z)
    public val stqq: Vec4 get() = Vec4(x, y, w, w)
    public val spss: Vec4 get() = Vec4(x, z, x, x)
    public val spst: Vec4 get() = Vec4(x, z, x, y)
    public val spsp: Vec4 get() = Vec4(x, z, x, z)
    public val spsq: Vec4 get() = Vec4(x, z, x, w)
    public val spts: Vec4 get() = Vec4(x, z, y, x)
    public val sptt: Vec4 get() = Vec4(x, z, y, y)
    public val sptp: Vec4 get() = Vec4(x, z, y, z)
    public val sptq: Vec4 get() = Vec4(x, z, y, w)
    public val spps: Vec4 get() = Vec4(x, z, z, x)
    public val sppt: Vec4 get() = Vec4(x, z, z, y)
    public val sppp: Vec4 get() = Vec4(x, z, z, z)
    public val sppq: Vec4 get() = Vec4(x, z, z, w)
    public val spqs: Vec4 get() = Vec4(x, z, w, x)
    public val spqt: Vec4 get() = Vec4(x, z, w, y)
    public val spqp: Vec4 get() = Vec4(x, z, w, z)
    public val spqq: Vec4 get() = Vec4(x, z, w, w)
    public val sqss: Vec4 get() = Vec4(x, w, x, x)
    public val sqst: Vec4 get() = Vec4(x, w, x, y)
    public val sqsp: Vec4 get() = Vec4(x, w, x, z)
    public val sqsq: Vec4 get() = Vec4(x, w, x, w)
    public val sqts: Vec4 get() = Vec4(x, w, y, x)
    public val sqtt: Vec4 get() = Vec4(x, w, y, y)
    public val sqtp: Vec4 get() = Vec4(x, w, y, z)
    public val sqtq: Vec4 get() = Vec4(x, w, y, w)
    public val sqps: Vec4 get() = Vec4(x, w, z, x)
    public val sqpt: Vec4 get() = Vec4(x, w, z, y)
    public val sqpp: Vec4 get() = Vec4(x, w, z, z)
    public val sqpq: Vec4 get() = Vec4(x, w, z, w)
    public val sqqs: Vec4 get() = Vec4(x, w, w, x)
    public val sqqt: Vec4 get() = Vec4(x, w, w, y)
    public val sqqp: Vec4 get() = Vec4(x, w, w, z)
    public val sqqq: Vec4 get() = Vec4(x, w, w, w)
    public val tsss: Vec4 get() = Vec4(y, x, x, x)
    public val tsst: Vec4 get() = Vec4(y, x, x, y)
    public val tssp: Vec4 get() = Vec4(y, x, x, z)
    public val tssq: Vec4 get() = Vec4(y, x, x, w)
    public val tsts: Vec4 get() = Vec4(y, x, y, x)
    public val tstt: Vec4 get() = Vec4(y, x, y, y)
    public val tstp: Vec4 get() = Vec4(y, x, y, z)
    public val tstq: Vec4 get() = Vec4(y, x, y, w)
    public val tsps: Vec4 get() = Vec4(y, x, z, x)
    public val tspt: Vec4 get() = Vec4(y, x, z, y)
    public val tspp: Vec4 get() = Vec4(y, x, z, z)
    public val tspq: Vec4 get() = Vec4(y, x, z, w)
    public val tsqs: Vec4 get() = Vec4(y, x, w, x)
    public val tsqt: Vec4 get() = Vec4(y, x, w, y)
    public val tsqp: Vec4 get() = Vec4(y, x, w, z)
    public val tsqq: Vec4 get() = Vec4(y, x, w, w)
    public val ttss: Vec4 get() = Vec4(y, y, x, x)
    public val ttst: Vec4 get() = Vec4(y, y, x, y)
    public val ttsp: Vec4 get() = Vec4(y, y, x, z)
    public val ttsq: Vec4 get() = Vec4(y, y, x, w)
    public val ttts: Vec4 get() = Vec4(y, y, y, x)
    public val tttt: Vec4 get() = Vec4(y, y, y, y)
    public val tttp: Vec4 get() = Vec4(y, y, y, z)
    public val tttq: Vec4 get() = Vec4(y, y, y, w)
    public val ttps: Vec4 get() = Vec4(y, y, z, x)
    public val ttpt: Vec4 get() = Vec4(y, y, z, y)
    public val ttpp: Vec4 get() = Vec4(y, y, z, z)
    public val ttpq: Vec4 get() = Vec4(y, y, z, w)
    public val ttqs: Vec4 get() = Vec4(y, y, w, x)
    public val ttqt: Vec4 get() = Vec4(y, y, w, y)
    public val ttqp: Vec4 get() = Vec4(y, y, w, z)
    public val ttqq: Vec4 get() = Vec4(y, y, w, w)
    public val tpss: Vec4 get() = Vec4(y, z, x, x)
    public val tpst: Vec4 get() = Vec4(y, z, x, y)
    public val tpsp: Vec4 get() = Vec4(y, z, x, z)
    public val tpsq: Vec4 get() = Vec4(y, z, x, w)
    public val tpts: Vec4 get() = Vec4(y, z, y, x)
    public val tptt: Vec4 get() = Vec4(y, z, y, y)
    public val tptp: Vec4 get() = Vec4(y, z, y, z)
    public val tptq: Vec4 get() = Vec4(y, z, y, w)
    public val tpps: Vec4 get() = Vec4(y, z, z, x)
    public val tppt: Vec4 get() = Vec4(y, z, z, y)
    public val tppp: Vec4 get() = Vec4(y, z, z, z)
    public val tppq: Vec4 get() = Vec4(y, z, z, w)
    public val tpqs: Vec4 get() = Vec4(y, z, w, x)
    public val tpqt: Vec4 get() = Vec4(y, z, w, y)
    public val tpqp: Vec4 get() = Vec4(y, z, w, z)
    public val tpqq: Vec4 get() = Vec4(y, z, w, w)
    public val tqss: Vec4 get() = Vec4(y, w, x, x)
    public val tqst: Vec4 get() = Vec4(y, w, x, y)
    public val tqsp: Vec4 get() = Vec4(y, w, x, z)
    public val tqsq: Vec4 get() = Vec4(y, w, x, w)
    public val tqts: Vec4 get() = Vec4(y, w, y, x)
    public val tqtt: Vec4 get() = Vec4(y, w, y, y)
    public val tqtp: Vec4 get() = Vec4(y, w, y, z)
    public val tqtq: Vec4 get() = Vec4(y, w, y, w)
    public val tqps: Vec4 get() = Vec4(y, w, z, x)
    public val tqpt: Vec4 get() = Vec4(y, w, z, y)
    public val tqpp: Vec4 get() = Vec4(y, w, z, z)
    public val tqpq: Vec4 get() = Vec4(y, w, z, w)
    public val tqqs: Vec4 get() = Vec4(y, w, w, x)
    public val tqqt: Vec4 get() = Vec4(y, w, w, y)
    public val tqqp: Vec4 get() = Vec4(y, w, w, z)
    public val tqqq: Vec4 get() = Vec4(y, w, w, w)
    public val psss: Vec4 get() = Vec4(z, x, x, x)
    public val psst: Vec4 get() = Vec4(z, x, x, y)
    public val pssp: Vec4 get() = Vec4(z, x, x, z)
    public val pssq: Vec4 get() = Vec4(z, x, x, w)
    public val psts: Vec4 get() = Vec4(z, x, y, x)
    public val pstt: Vec4 get() = Vec4(z, x, y, y)
    public val pstp: Vec4 get() = Vec4(z, x, y, z)
    public val pstq: Vec4 get() = Vec4(z, x, y, w)
    public val psps: Vec4 get() = Vec4(z, x, z, x)
    public val pspt: Vec4 get() = Vec4(z, x, z, y)
    public val pspp: Vec4 get() = Vec4(z, x, z, z)
    public val pspq: Vec4 get() = Vec4(z, x, z, w)
    public val psqs: Vec4 get() = Vec4(z, x, w, x)
    public val psqt: Vec4 get() = Vec4(z, x, w, y)
    public val psqp: Vec4 get() = Vec4(z, x, w, z)
    public val psqq: Vec4 get() = Vec4(z, x, w, w)
    public val ptss: Vec4 get() = Vec4(z, y, x, x)
    public val ptst: Vec4 get() = Vec4(z, y, x, y)
    public val ptsp: Vec4 get() = Vec4(z, y, x, z)
    public val ptsq: Vec4 get() = Vec4(z, y, x, w)
    public val ptts: Vec4 get() = Vec4(z, y, y, x)
    public val pttt: Vec4 get() = Vec4(z, y, y, y)
    public val pttp: Vec4 get() = Vec4(z, y, y, z)
    public val pttq: Vec4 get() = Vec4(z, y, y, w)
    public val ptps: Vec4 get() = Vec4(z, y, z, x)
    public val ptpt: Vec4 get() = Vec4(z, y, z, y)
    public val ptpp: Vec4 get() = Vec4(z, y, z, z)
    public val ptpq: Vec4 get() = Vec4(z, y, z, w)
    public val ptqs: Vec4 get() = Vec4(z, y, w, x)
    public val ptqt: Vec4 get() = Vec4(z, y, w, y)
    public val ptqp: Vec4 get() = Vec4(z, y, w, z)
    public val ptqq: Vec4 get() = Vec4(z, y, w, w)
    public val ppss: Vec4 get() = Vec4(z, z, x, x)
    public val ppst: Vec4 get() = Vec4(z, z, x, y)
    public val ppsp: Vec4 get() = Vec4(z, z, x, z)
    public val ppsq: Vec4 get() = Vec4(z, z, x, w)
    public val ppts: Vec4 get() = Vec4(z, z, y, x)
    public val pptt: Vec4 get() = Vec4(z, z, y, y)
    public val pptp: Vec4 get() = Vec4(z, z, y, z)
    public val pptq: Vec4 get() = Vec4(z, z, y, w)
    public val ppps: Vec4 get() = Vec4(z, z, z, x)
    public val pppt: Vec4 get() = Vec4(z, z, z, y)
    public val pppp: Vec4 get() = Vec4(z, z, z, z)
    public val pppq: Vec4 get() = Vec4(z, z, z, w)
    public val ppqs: Vec4 get() = Vec4(z, z, w, x)
    public val ppqt: Vec4 get() = Vec4(z, z, w, y)
    public val ppqp: Vec4 get() = Vec4(z, z, w, z)
    public val ppqq: Vec4 get() = Vec4(z, z, w, w)
    public val pqss: Vec4 get() = Vec4(z, w, x, x)
    public val pqst: Vec4 get() = Vec4(z, w, x, y)
    public val pqsp: Vec4 get() = Vec4(z, w, x, z)
    public val pqsq: Vec4 get() = Vec4(z, w, x, w)
    public val pqts: Vec4 get() = Vec4(z, w, y, x)
    public val pqtt: Vec4 get() = Vec4(z, w, y, y)
    public val pqtp: Vec4 get() = Vec4(z, w, y, z)
    public val pqtq: Vec4 get() = Vec4(z, w, y, w)
    public val pqps: Vec4 get() = Vec4(z, w, z, x)
    public val pqpt: Vec4 get() = Vec4(z, w, z, y)
    public val pqpp: Vec4 get() = Vec4(z, w, z, z)
    public val pqpq: Vec4 get() = Vec4(z, w, z, w)
    public val pqqs: Vec4 get() = Vec4(z, w, w, x)
    public val pqqt: Vec4 get() = Vec4(z, w, w, y)
    public val pqqp: Vec4 get() = Vec4(z, w, w, z)
    public val pqqq: Vec4 get() = Vec4(z, w, w, w)
    public val qsss: Vec4 get() = Vec4(w, x, x, x)
    public val qsst: Vec4 get() = Vec4(w, x, x, y)
    public val qssp: Vec4 get() = Vec4(w, x, x, z)
    public val qssq: Vec4 get() = Vec4(w, x, x, w)
    public val qsts: Vec4 get() = Vec4(w, x, y, x)
    public val qstt: Vec4 get() = Vec4(w, x, y, y)
    public val qstp: Vec4 get() = Vec4(w, x, y, z)
    public val qstq: Vec4 get() = Vec4(w, x, y, w)
    public val qsps: Vec4 get() = Vec4(w, x, z, x)
    public val qspt: Vec4 get() = Vec4(w, x, z, y)
    public val qspp: Vec4 get() = Vec4(w, x, z, z)
    public val qspq: Vec4 get() = Vec4(w, x, z, w)
    public val qsqs: Vec4 get() = Vec4(w, x, w, x)
    public val qsqt: Vec4 get() = Vec4(w, x, w, y)
    public val qsqp: Vec4 get() = Vec4(w, x, w, z)
    public val qsqq: Vec4 get() = Vec4(w, x, w, w)
    public val qtss: Vec4 get() = Vec4(w, y, x, x)
    public val qtst: Vec4 get() = Vec4(w, y, x, y)
    public val qtsp: Vec4 get() = Vec4(w, y, x, z)
    public val qtsq: Vec4 get() = Vec4(w, y, x, w)
    public val qtts: Vec4 get() = Vec4(w, y, y, x)
    public val qttt: Vec4 get() = Vec4(w, y, y, y)
    public val qttp: Vec4 get() = Vec4(w, y, y, z)
    public val qttq: Vec4 get() = Vec4(w, y, y, w)
    public val qtps: Vec4 get() = Vec4(w, y, z, x)
    public val qtpt: Vec4 get() = Vec4(w, y, z, y)
    public val qtpp: Vec4 get() = Vec4(w, y, z, z)
    public val qtpq: Vec4 get() = Vec4(w, y, z, w)
    public val qtqs: Vec4 get() = Vec4(w, y, w, x)
    public val qtqt: Vec4 get() = Vec4(w, y, w, y)
    public val qtqp: Vec4 get() = Vec4(w, y, w, z)
    public val qtqq: Vec4 get() = Vec4(w, y, w, w)
    public val qpss: Vec4 get() = Vec4(w, z, x, x)
    public val qpst: Vec4 get() = Vec4(w, z, x, y)
    public val qpsp: Vec4 get() = Vec4(w, z, x, z)
    public val qpsq: Vec4 get() = Vec4(w, z, x, w)
    public val qpts: Vec4 get() = Vec4(w, z, y, x)
    public val qptt: Vec4 get() = Vec4(w, z, y, y)
    public val qptp: Vec4 get() = Vec4(w, z, y, z)
    public val qptq: Vec4 get() = Vec4(w, z, y, w)
    public val qpps: Vec4 get() = Vec4(w, z, z, x)
    public val qppt: Vec4 get() = Vec4(w, z, z, y)
    public val qppp: Vec4 get() = Vec4(w, z, z, z)
    public val qppq: Vec4 get() = Vec4(w, z, z, w)
    public val qpqs: Vec4 get() = Vec4(w, z, w, x)
    public val qpqt: Vec4 get() = Vec4(w, z, w, y)
    public val qpqp: Vec4 get() = Vec4(w, z, w, z)
    public val qpqq: Vec4 get() = Vec4(w, z, w, w)
    public val qqss: Vec4 get() = Vec4(w, w, x, x)
    public val qqst: Vec4 get() = Vec4(w, w, x, y)
    public val qqsp: Vec4 get() = Vec4(w, w, x, z)
    public val qqsq: Vec4 get() = Vec4(w, w, x, w)
    public val qqts: Vec4 get() = Vec4(w, w, y, x)
    public val qqtt: Vec4 get() = Vec4(w, w, y, y)
    public val qqtp: Vec4 get() = Vec4(w, w, y, z)
    public val qqtq: Vec4 get() = Vec4(w, w, y, w)
    public val qqps: Vec4 get() = Vec4(w, w, z, x)
    public val qqpt: Vec4 get() = Vec4(w, w, z, y)
    public val qqpp: Vec4 get() = Vec4(w, w, z, z)
    public val qqpq: Vec4 get() = Vec4(w, w, z, w)
    public val qqqs: Vec4 get() = Vec4(w, w, w, x)
    public val qqqt: Vec4 get() = Vec4(w, w, w, y)
    public val qqqp: Vec4 get() = Vec4(w, w, w, z)
    public val qqqq: Vec4 get() = Vec4(w, w, w, w)

    public val r: Float get() = x
    public val g: Float get() = y
    public val b: Float get() = z
    public val a: Float get() = w

    public val rr: Vec2 get() = Vec2(x, x)
    public val rg: Vec2 get() = Vec2(x, y)
    public val rb: Vec2 get() = Vec2(x, z)
    public val ra: Vec2 get() = Vec2(x, w)
    public val gr: Vec2 get() = Vec2(y, x)
    public val gg: Vec2 get() = Vec2(y, y)
    public val gb: Vec2 get() = Vec2(y, z)
    public val ga: Vec2 get() = Vec2(y, w)
    public val br: Vec2 get() = Vec2(z, x)
    public val bg: Vec2 get() = Vec2(z, y)
    public val bb: Vec2 get() = Vec2(z, z)
    public val ba: Vec2 get() = Vec2(z, w)
    public val ar: Vec2 get() = Vec2(w, x)
    public val ag: Vec2 get() = Vec2(w, y)
    public val ab: Vec2 get() = Vec2(w, z)
    public val aa: Vec2 get() = Vec2(w, w)

    public val rrr: Vec3 get() = Vec3(x, x, x)
    public val rrg: Vec3 get() = Vec3(x, x, y)
    public val rrb: Vec3 get() = Vec3(x, x, z)
    public val rra: Vec3 get() = Vec3(x, x, w)
    public val rgr: Vec3 get() = Vec3(x, y, x)
    public val rgg: Vec3 get() = Vec3(x, y, y)
    public val rgb: Vec3 get() = Vec3(x, y, z)
    public val rga: Vec3 get() = Vec3(x, y, w)
    public val rbr: Vec3 get() = Vec3(x, z, x)
    public val rbg: Vec3 get() = Vec3(x, z, y)
    public val rbb: Vec3 get() = Vec3(x, z, z)
    public val rba: Vec3 get() = Vec3(x, z, w)
    public val rar: Vec3 get() = Vec3(x, w, x)
    public val rag: Vec3 get() = Vec3(x, w, y)
    public val rab: Vec3 get() = Vec3(x, w, z)
    public val raa: Vec3 get() = Vec3(x, w, w)
    public val grr: Vec3 get() = Vec3(y, x, x)
    public val grg: Vec3 get() = Vec3(y, x, y)
    public val grb: Vec3 get() = Vec3(y, x, z)
    public val gra: Vec3 get() = Vec3(y, x, w)
    public val ggr: Vec3 get() = Vec3(y, y, x)
    public val ggg: Vec3 get() = Vec3(y, y, y)
    public val ggb: Vec3 get() = Vec3(y, y, z)
    public val gga: Vec3 get() = Vec3(y, y, w)
    public val gbr: Vec3 get() = Vec3(y, z, x)
    public val gbg: Vec3 get() = Vec3(y, z, y)
    public val gbb: Vec3 get() = Vec3(y, z, z)
    public val gba: Vec3 get() = Vec3(y, z, w)
    public val gar: Vec3 get() = Vec3(y, w, x)
    public val gag: Vec3 get() = Vec3(y, w, y)
    public val gab: Vec3 get() = Vec3(y, w, z)
    public val gaa: Vec3 get() = Vec3(y, w, w)
    public val brr: Vec3 get() = Vec3(z, x, x)
    public val brg: Vec3 get() = Vec3(z, x, y)
    public val brb: Vec3 get() = Vec3(z, x, z)
    public val bra: Vec3 get() = Vec3(z, x, w)
    public val bgr: Vec3 get() = Vec3(z, y, x)
    public val bgg: Vec3 get() = Vec3(z, y, y)
    public val bgb: Vec3 get() = Vec3(z, y, z)
    public val bga: Vec3 get() = Vec3(z, y, w)
    public val bbr: Vec3 get() = Vec3(z, z, x)
    public val bbg: Vec3 get() = Vec3(z, z, y)
    public val bbb: Vec3 get() = Vec3(z, z, z)
    public val bba: Vec3 get() = Vec3(z, z, w)
    public val bar: Vec3 get() = Vec3(z, w, x)
    public val bag: Vec3 get() = Vec3(z, w, y)
    public val bab: Vec3 get() = Vec3(z, w, z)
    public val baa: Vec3 get() = Vec3(z, w, w)
    public val arr: Vec3 get() = Vec3(w, x, x)
    public val arg: Vec3 get() = Vec3(w, x, y)
    public val arb: Vec3 get() = Vec3(w, x, z)
    public val ara: Vec3 get() = Vec3(w, x, w)
    public val agr: Vec3 get() = Vec3(w, y, x)
    public val agg: Vec3 get() = Vec3(w, y, y)
    public val agb: Vec3 get() = Vec3(w, y, z)
    public val aga: Vec3 get() = Vec3(w, y, w)
    public val abr: Vec3 get() = Vec3(w, z, x)
    public val abg: Vec3 get() = Vec3(w, z, y)
    public val abb: Vec3 get() = Vec3(w, z, z)
    public val aba: Vec3 get() = Vec3(w, z, w)
    public val aar: Vec3 get() = Vec3(w, w, x)
    public val aag: Vec3 get() = Vec3(w, w, y)
    public val aab: Vec3 get() = Vec3(w, w, z)
    public val aaa: Vec3 get() = Vec3(w, w, w)

    public val rrrr: Vec4 get() = Vec4(x, x, x, x)
    public val rrrg: Vec4 get() = Vec4(x, x, x, y)
    public val rrrb: Vec4 get() = Vec4(x, x, x, z)
    public val rrra: Vec4 get() = Vec4(x, x, x, w)
    public val rrgr: Vec4 get() = Vec4(x, x, y, x)
    public val rrgg: Vec4 get() = Vec4(x, x, y, y)
    public val rrgb: Vec4 get() = Vec4(x, x, y, z)
    public val rrga: Vec4 get() = Vec4(x, x, y, w)
    public val rrbr: Vec4 get() = Vec4(x, x, z, x)
    public val rrbg: Vec4 get() = Vec4(x, x, z, y)
    public val rrbb: Vec4 get() = Vec4(x, x, z, z)
    public val rrba: Vec4 get() = Vec4(x, x, z, w)
    public val rrar: Vec4 get() = Vec4(x, x, w, x)
    public val rrag: Vec4 get() = Vec4(x, x, w, y)
    public val rrab: Vec4 get() = Vec4(x, x, w, z)
    public val rraa: Vec4 get() = Vec4(x, x, w, w)
    public val rgrr: Vec4 get() = Vec4(x, y, x, x)
    public val rgrg: Vec4 get() = Vec4(x, y, x, y)
    public val rgrb: Vec4 get() = Vec4(x, y, x, z)
    public val rgra: Vec4 get() = Vec4(x, y, x, w)
    public val rggr: Vec4 get() = Vec4(x, y, y, x)
    public val rggg: Vec4 get() = Vec4(x, y, y, y)
    public val rggb: Vec4 get() = Vec4(x, y, y, z)
    public val rgga: Vec4 get() = Vec4(x, y, y, w)
    public val rgbr: Vec4 get() = Vec4(x, y, z, x)
    public val rgbg: Vec4 get() = Vec4(x, y, z, y)
    public val rgbb: Vec4 get() = Vec4(x, y, z, z)
    public val rgba: Vec4 get() = Vec4(x, y, z, w)
    public val rgar: Vec4 get() = Vec4(x, y, w, x)
    public val rgag: Vec4 get() = Vec4(x, y, w, y)
    public val rgab: Vec4 get() = Vec4(x, y, w, z)
    public val rgaa: Vec4 get() = Vec4(x, y, w, w)
    public val rbrr: Vec4 get() = Vec4(x, z, x, x)
    public val rbrg: Vec4 get() = Vec4(x, z, x, y)
    public val rbrb: Vec4 get() = Vec4(x, z, x, z)
    public val rbra: Vec4 get() = Vec4(x, z, x, w)
    public val rbgr: Vec4 get() = Vec4(x, z, y, x)
    public val rbgg: Vec4 get() = Vec4(x, z, y, y)
    public val rbgb: Vec4 get() = Vec4(x, z, y, z)
    public val rbga: Vec4 get() = Vec4(x, z, y, w)
    public val rbbr: Vec4 get() = Vec4(x, z, z, x)
    public val rbbg: Vec4 get() = Vec4(x, z, z, y)
    public val rbbb: Vec4 get() = Vec4(x, z, z, z)
    public val rbba: Vec4 get() = Vec4(x, z, z, w)
    public val rbar: Vec4 get() = Vec4(x, z, w, x)
    public val rbag: Vec4 get() = Vec4(x, z, w, y)
    public val rbab: Vec4 get() = Vec4(x, z, w, z)
    public val rbaa: Vec4 get() = Vec4(x, z, w, w)
    public val rarr: Vec4 get() = Vec4(x, w, x, x)
    public val rarg: Vec4 get() = Vec4(x, w, x, y)
    public val rarb: Vec4 get() = Vec4(x, w, x, z)
    public val rara: Vec4 get() = Vec4(x, w, x, w)
    public val ragr: Vec4 get() = Vec4(x, w, y, x)
    public val ragg: Vec4 get() = Vec4(x, w, y, y)
    public val ragb: Vec4 get() = Vec4(x, w, y, z)
    public val raga: Vec4 get() = Vec4(x, w, y, w)
    public val rabr: Vec4 get() = Vec4(x, w, z, x)
    public val rabg: Vec4 get() = Vec4(x, w, z, y)
    public val rabb: Vec4 get() = Vec4(x, w, z, z)
    public val raba: Vec4 get() = Vec4(x, w, z, w)
    public val raar: Vec4 get() = Vec4(x, w, w, x)
    public val raag: Vec4 get() = Vec4(x, w, w, y)
    public val raab: Vec4 get() = Vec4(x, w, w, z)
    public val raaa: Vec4 get() = Vec4(x, w, w, w)
    public val grrr: Vec4 get() = Vec4(y, x, x, x)
    public val grrg: Vec4 get() = Vec4(y, x, x, y)
    public val grrb: Vec4 get() = Vec4(y, x, x, z)
    public val grra: Vec4 get() = Vec4(y, x, x, w)
    public val grgr: Vec4 get() = Vec4(y, x, y, x)
    public val grgg: Vec4 get() = Vec4(y, x, y, y)
    public val grgb: Vec4 get() = Vec4(y, x, y, z)
    public val grga: Vec4 get() = Vec4(y, x, y, w)
    public val grbr: Vec4 get() = Vec4(y, x, z, x)
    public val grbg: Vec4 get() = Vec4(y, x, z, y)
    public val grbb: Vec4 get() = Vec4(y, x, z, z)
    public val grba: Vec4 get() = Vec4(y, x, z, w)
    public val grar: Vec4 get() = Vec4(y, x, w, x)
    public val grag: Vec4 get() = Vec4(y, x, w, y)
    public val grab: Vec4 get() = Vec4(y, x, w, z)
    public val graa: Vec4 get() = Vec4(y, x, w, w)
    public val ggrr: Vec4 get() = Vec4(y, y, x, x)
    public val ggrg: Vec4 get() = Vec4(y, y, x, y)
    public val ggrb: Vec4 get() = Vec4(y, y, x, z)
    public val ggra: Vec4 get() = Vec4(y, y, x, w)
    public val gggr: Vec4 get() = Vec4(y, y, y, x)
    public val gggg: Vec4 get() = Vec4(y, y, y, y)
    public val gggb: Vec4 get() = Vec4(y, y, y, z)
    public val ggga: Vec4 get() = Vec4(y, y, y, w)
    public val ggbr: Vec4 get() = Vec4(y, y, z, x)
    public val ggbg: Vec4 get() = Vec4(y, y, z, y)
    public val ggbb: Vec4 get() = Vec4(y, y, z, z)
    public val ggba: Vec4 get() = Vec4(y, y, z, w)
    public val ggar: Vec4 get() = Vec4(y, y, w, x)
    public val ggag: Vec4 get() = Vec4(y, y, w, y)
    public val ggab: Vec4 get() = Vec4(y, y, w, z)
    public val ggaa: Vec4 get() = Vec4(y, y, w, w)
    public val gbrr: Vec4 get() = Vec4(y, z, x, x)
    public val gbrg: Vec4 get() = Vec4(y, z, x, y)
    public val gbrb: Vec4 get() = Vec4(y, z, x, z)
    public val gbra: Vec4 get() = Vec4(y, z, x, w)
    public val gbgr: Vec4 get() = Vec4(y, z, y, x)
    public val gbgg: Vec4 get() = Vec4(y, z, y, y)
    public val gbgb: Vec4 get() = Vec4(y, z, y, z)
    public val gbga: Vec4 get() = Vec4(y, z, y, w)
    public val gbbr: Vec4 get() = Vec4(y, z, z, x)
    public val gbbg: Vec4 get() = Vec4(y, z, z, y)
    public val gbbb: Vec4 get() = Vec4(y, z, z, z)
    public val gbba: Vec4 get() = Vec4(y, z, z, w)
    public val gbar: Vec4 get() = Vec4(y, z, w, x)
    public val gbag: Vec4 get() = Vec4(y, z, w, y)
    public val gbab: Vec4 get() = Vec4(y, z, w, z)
    public val gbaa: Vec4 get() = Vec4(y, z, w, w)
    public val garr: Vec4 get() = Vec4(y, w, x, x)
    public val garg: Vec4 get() = Vec4(y, w, x, y)
    public val garb: Vec4 get() = Vec4(y, w, x, z)
    public val gara: Vec4 get() = Vec4(y, w, x, w)
    public val gagr: Vec4 get() = Vec4(y, w, y, x)
    public val gagg: Vec4 get() = Vec4(y, w, y, y)
    public val gagb: Vec4 get() = Vec4(y, w, y, z)
    public val gaga: Vec4 get() = Vec4(y, w, y, w)
    public val gabr: Vec4 get() = Vec4(y, w, z, x)
    public val gabg: Vec4 get() = Vec4(y, w, z, y)
    public val gabb: Vec4 get() = Vec4(y, w, z, z)
    public val gaba: Vec4 get() = Vec4(y, w, z, w)
    public val gaar: Vec4 get() = Vec4(y, w, w, x)
    public val gaag: Vec4 get() = Vec4(y, w, w, y)
    public val gaab: Vec4 get() = Vec4(y, w, w, z)
    public val gaaa: Vec4 get() = Vec4(y, w, w, w)
    public val brrr: Vec4 get() = Vec4(z, x, x, x)
    public val brrg: Vec4 get() = Vec4(z, x, x, y)
    public val brrb: Vec4 get() = Vec4(z, x, x, z)
    public val brra: Vec4 get() = Vec4(z, x, x, w)
    public val brgr: Vec4 get() = Vec4(z, x, y, x)
    public val brgg: Vec4 get() = Vec4(z, x, y, y)
    public val brgb: Vec4 get() = Vec4(z, x, y, z)
    public val brga: Vec4 get() = Vec4(z, x, y, w)
    public val brbr: Vec4 get() = Vec4(z, x, z, x)
    public val brbg: Vec4 get() = Vec4(z, x, z, y)
    public val brbb: Vec4 get() = Vec4(z, x, z, z)
    public val brba: Vec4 get() = Vec4(z, x, z, w)
    public val brar: Vec4 get() = Vec4(z, x, w, x)
    public val brag: Vec4 get() = Vec4(z, x, w, y)
    public val brab: Vec4 get() = Vec4(z, x, w, z)
    public val braa: Vec4 get() = Vec4(z, x, w, w)
    public val bgrr: Vec4 get() = Vec4(z, y, x, x)
    public val bgrg: Vec4 get() = Vec4(z, y, x, y)
    public val bgrb: Vec4 get() = Vec4(z, y, x, z)
    public val bgra: Vec4 get() = Vec4(z, y, x, w)
    public val bggr: Vec4 get() = Vec4(z, y, y, x)
    public val bggg: Vec4 get() = Vec4(z, y, y, y)
    public val bggb: Vec4 get() = Vec4(z, y, y, z)
    public val bgga: Vec4 get() = Vec4(z, y, y, w)
    public val bgbr: Vec4 get() = Vec4(z, y, z, x)
    public val bgbg: Vec4 get() = Vec4(z, y, z, y)
    public val bgbb: Vec4 get() = Vec4(z, y, z, z)
    public val bgba: Vec4 get() = Vec4(z, y, z, w)
    public val bgar: Vec4 get() = Vec4(z, y, w, x)
    public val bgag: Vec4 get() = Vec4(z, y, w, y)
    public val bgab: Vec4 get() = Vec4(z, y, w, z)
    public val bgaa: Vec4 get() = Vec4(z, y, w, w)
    public val bbrr: Vec4 get() = Vec4(z, z, x, x)
    public val bbrg: Vec4 get() = Vec4(z, z, x, y)
    public val bbrb: Vec4 get() = Vec4(z, z, x, z)
    public val bbra: Vec4 get() = Vec4(z, z, x, w)
    public val bbgr: Vec4 get() = Vec4(z, z, y, x)
    public val bbgg: Vec4 get() = Vec4(z, z, y, y)
    public val bbgb: Vec4 get() = Vec4(z, z, y, z)
    public val bbga: Vec4 get() = Vec4(z, z, y, w)
    public val bbbr: Vec4 get() = Vec4(z, z, z, x)
    public val bbbg: Vec4 get() = Vec4(z, z, z, y)
    public val bbbb: Vec4 get() = Vec4(z, z, z, z)
    public val bbba: Vec4 get() = Vec4(z, z, z, w)
    public val bbar: Vec4 get() = Vec4(z, z, w, x)
    public val bbag: Vec4 get() = Vec4(z, z, w, y)
    public val bbab: Vec4 get() = Vec4(z, z, w, z)
    public val bbaa: Vec4 get() = Vec4(z, z, w, w)
    public val barr: Vec4 get() = Vec4(z, w, x, x)
    public val barg: Vec4 get() = Vec4(z, w, x, y)
    public val barb: Vec4 get() = Vec4(z, w, x, z)
    public val bara: Vec4 get() = Vec4(z, w, x, w)
    public val bagr: Vec4 get() = Vec4(z, w, y, x)
    public val bagg: Vec4 get() = Vec4(z, w, y, y)
    public val bagb: Vec4 get() = Vec4(z, w, y, z)
    public val baga: Vec4 get() = Vec4(z, w, y, w)
    public val babr: Vec4 get() = Vec4(z, w, z, x)
    public val babg: Vec4 get() = Vec4(z, w, z, y)
    public val babb: Vec4 get() = Vec4(z, w, z, z)
    public val baba: Vec4 get() = Vec4(z, w, z, w)
    public val baar: Vec4 get() = Vec4(z, w, w, x)
    public val baag: Vec4 get() = Vec4(z, w, w, y)
    public val baab: Vec4 get() = Vec4(z, w, w, z)
    public val baaa: Vec4 get() = Vec4(z, w, w, w)
    public val arrr: Vec4 get() = Vec4(w, x, x, x)
    public val arrg: Vec4 get() = Vec4(w, x, x, y)
    public val arrb: Vec4 get() = Vec4(w, x, x, z)
    public val arra: Vec4 get() = Vec4(w, x, x, w)
    public val argr: Vec4 get() = Vec4(w, x, y, x)
    public val argg: Vec4 get() = Vec4(w, x, y, y)
    public val argb: Vec4 get() = Vec4(w, x, y, z)
    public val arga: Vec4 get() = Vec4(w, x, y, w)
    public val arbr: Vec4 get() = Vec4(w, x, z, x)
    public val arbg: Vec4 get() = Vec4(w, x, z, y)
    public val arbb: Vec4 get() = Vec4(w, x, z, z)
    public val arba: Vec4 get() = Vec4(w, x, z, w)
    public val arar: Vec4 get() = Vec4(w, x, w, x)
    public val arag: Vec4 get() = Vec4(w, x, w, y)
    public val arab: Vec4 get() = Vec4(w, x, w, z)
    public val araa: Vec4 get() = Vec4(w, x, w, w)
    public val agrr: Vec4 get() = Vec4(w, y, x, x)
    public val agrg: Vec4 get() = Vec4(w, y, x, y)
    public val agrb: Vec4 get() = Vec4(w, y, x, z)
    public val agra: Vec4 get() = Vec4(w, y, x, w)
    public val aggr: Vec4 get() = Vec4(w, y, y, x)
    public val aggg: Vec4 get() = Vec4(w, y, y, y)
    public val aggb: Vec4 get() = Vec4(w, y, y, z)
    public val agga: Vec4 get() = Vec4(w, y, y, w)
    public val agbr: Vec4 get() = Vec4(w, y, z, x)
    public val agbg: Vec4 get() = Vec4(w, y, z, y)
    public val agbb: Vec4 get() = Vec4(w, y, z, z)
    public val agba: Vec4 get() = Vec4(w, y, z, w)
    public val agar: Vec4 get() = Vec4(w, y, w, x)
    public val agag: Vec4 get() = Vec4(w, y, w, y)
    public val agab: Vec4 get() = Vec4(w, y, w, z)
    public val agaa: Vec4 get() = Vec4(w, y, w, w)
    public val abrr: Vec4 get() = Vec4(w, z, x, x)
    public val abrg: Vec4 get() = Vec4(w, z, x, y)
    public val abrb: Vec4 get() = Vec4(w, z, x, z)
    public val abra: Vec4 get() = Vec4(w, z, x, w)
    public val abgr: Vec4 get() = Vec4(w, z, y, x)
    public val abgg: Vec4 get() = Vec4(w, z, y, y)
    public val abgb: Vec4 get() = Vec4(w, z, y, z)
    public val abga: Vec4 get() = Vec4(w, z, y, w)
    public val abbr: Vec4 get() = Vec4(w, z, z, x)
    public val abbg: Vec4 get() = Vec4(w, z, z, y)
    public val abbb: Vec4 get() = Vec4(w, z, z, z)
    public val abba: Vec4 get() = Vec4(w, z, z, w)
    public val abar: Vec4 get() = Vec4(w, z, w, x)
    public val abag: Vec4 get() = Vec4(w, z, w, y)
    public val abab: Vec4 get() = Vec4(w, z, w, z)
    public val abaa: Vec4 get() = Vec4(w, z, w, w)
    public val aarr: Vec4 get() = Vec4(w, w, x, x)
    public val aarg: Vec4 get() = Vec4(w, w, x, y)
    public val aarb: Vec4 get() = Vec4(w, w, x, z)
    public val aara: Vec4 get() = Vec4(w, w, x, w)
    public val aagr: Vec4 get() = Vec4(w, w, y, x)
    public val aagg: Vec4 get() = Vec4(w, w, y, y)
    public val aagb: Vec4 get() = Vec4(w, w, y, z)
    public val aaga: Vec4 get() = Vec4(w, w, y, w)
    public val aabr: Vec4 get() = Vec4(w, w, z, x)
    public val aabg: Vec4 get() = Vec4(w, w, z, y)
    public val aabb: Vec4 get() = Vec4(w, w, z, z)
    public val aaba: Vec4 get() = Vec4(w, w, z, w)
    public val aaar: Vec4 get() = Vec4(w, w, w, x)
    public val aaag: Vec4 get() = Vec4(w, w, w, y)
    public val aaab: Vec4 get() = Vec4(w, w, w, z)
    public val aaaa: Vec4 get() = Vec4(w, w, w, w)
}
